---
- name: Deploy OpenClaw servers
  hosts: openclaw_servers
  become: true
  vars_files:
    - ../vars/common.yml
    - ../vars/vault.yml
  roles:
    - openclaw.installer.openclaw
    - debian
    - tailscale
    - mise
    - openclaw
  vars:
    ansible_python_interpreter: /usr/bin/python3
    openclaw_user: "{{ openclaw_default_user }}"
    debian_user: "{{ openclaw_default_user }}"
    mise_user: "{{ openclaw_default_user }}"
    security_user: "{{ openclaw_default_user }}"
    discord_allowed_users: "{{ default_discord_allowed_users }}"
    discord_home_channel: "{{ default_discord_home_channel }}"
    git_user_name: "{{ default_git_user_name }}"
    git_user_email: "{{ default_git_user_email }}"
