---
- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Update CA certificates
  ansible.builtin.command: update-ca-certificates
  changed_when: true
